//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// Tue Jul 30 2019 21:10:02
//
//      Input file      : 
//      Component name  : armsmsspackage
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------

// ***************************************************************************************** 
// Constants and type declarations for memory subsystem for ARM core simualtion 
// Designed by Ruslan Lepetenok 
// Modified 07.02.2003 
//**************************************************************************************************** 

`ifndef armsmsspackage
`define armsmsspackage


parameter                       DecoderAdrWidth = 16;
parameter                       CSlowMemAdrWidth = 16;		// Address width for slow memory detection (CLKEN generation) 
parameter                       CAbtMemAdrWidth = 16;		// Address width for memory abort detection (ABORT generation) 

// Device addresses 
parameter [DecoderAdrWidth-1:0] CROMAddress = 16'h0030;
parameter [DecoderAdrWidth-1:0] CRAMAddress = 16'h0000;
parameter [DecoderAdrWidth-1:0] CDevCAddress = 16'h0001;
parameter [DecoderAdrWidth-1:0] CDevDAddress = 16'h0002;

// Memory remapper register addrerss 
parameter [31:0]                CRemapperAddress = 32'hFFE00020;

// Name of log file for bus 
parameter [32*8:1]              CLogFileName = "BusLog.txt";

// Function declaration 

// Functions	 
function integer LOG2;
   input                           Number;
   reg                             Temp;
   integer                         i;
begin
   if (Number == 1)
      LOG2 = 0;
   else
   begin
      for (i = 1; i <= 0; i = i + 1)
      begin
         Temp = 2 * Temp;
         if (Temp >= Number)
            LOG2 = i;
      end
      LOG2 = 0;
   end
end
endfunction

`endif
