//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// Tue Jul 30 2019 21:10:25
//
//      Input file      : 
//      Component name  : msscomppackage
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------

// *****************************************************************************************
// Components for ARM memory subsystem (simulation)
// Designed by Ruslan Lepetenok
// Modified 02.02.2003
//****************************************************************************************************

`ifndef msscomppackage
`define msscomppackage

`include "armsmsspackage.v"

`endif

// Bus monitor control
// ROM parameters
// RAM size (in bytes)
// Memory address(or range) for ABORT
// Number of aborts
// Memory address(or range) for CLKEN
// Number of wait states
// Global control signals
// Address class signals
// Memory request signals
// Data timed signals
// Global control output


// Global control signals
// Address and data



// Global control signals
// Address class signals
// Outputs


// Address class signals
// Outputs


// Control inputs
// Input data
// Data output


// Global control signals
// Memory request signals
// ADDR
// Output

// Global control signals
// Memory request signals
// ADDR and data
// Output


// Global control signals
// Address and data
// Memory select signals for remapping


// Global control signals
// Transaction type

// Global control signals
// Address class signals
// Memory request signals
// Data timed signals


