//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// Tue Jul 30 2019 21:10:38
//
//      Input file      : 
//      Component name  : resltbitmask
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------

//**************************************************************************************************** 
// This module cleares/sets bit 0 and clears 1 of ALU bus for ARM7TDMI-S processor 
// Designed by Ruslan Lepetenok 
// Modified 18.12.2002 
//**************************************************************************************************** 

module resltbitmask(
   DataIn,
   DataOut,
   ClrBitZero,
   ClrBitOne,
   SetBitZero
);
   // Data 
   input [31:0]  DataIn;
   output [31:0] DataOut;
   // Control 
   input         ClrBitZero;
   input         ClrBitOne;
   input         SetBitZero;
   
   
   assign DataOut[31:2] = DataIn[31:2];
   
   // Nomal mode (pass bit[0]) 
   assign DataOut[0] = (DataIn[0] & (~(ClrBitZero | SetBitZero))) | SetBitZero;		// Set bit[0] - Thumb mode Branch with link (LR bit[0]='1') 
   
   assign DataOut[1] = (ClrBitOne == 1'b1) ? 1'b0 : 
                       DataIn[1];
   
endmodule

