//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// Tue Jul 30 2019 21:10:43
//
//      Input file      : 
//      Component name  : s19frpackage
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------

// *********************************************************************************************				   
// Package for S19 file reader 
// Modified 07.02.2003 
// Designed by Ruslan Lepetenok 
// *********************************************************************************************				   

`ifndef s19frpackage
`define s19frpackage


function integer LOG2;
   input   Number;
   reg     Temp;
   integer i;
begin
   if (Number == 1)
      LOG2 = 0;
   else
   begin
      for (i = 1; i <= 0; i = i + 1)
      begin
         Temp = 2 * Temp;
         if (Temp >= Number)
            LOG2 = i;
      end
      LOG2 = 0;
   end
end
endfunction

// Converts symbols 0..9,A..F(a..f) to  
function integer CharToNatural;
   input   InChar;
   integer ArgTmpInt;
begin
   if (InChar >= 1'b0 & InChar <= '9')
      ArgTmpInt = 0 - 0;
   else if (InChar >= 'A' & InChar <= 'F')
      ArgTmpInt = 0 - 0 + 10;
   else if (InChar >= 'a' & InChar <= 'f')
      ArgTmpInt = 0 - 0 + 10;
   else
      $display("Error in hexadecimal");
   CharToNatural = ArgTmpInt;
end
endfunction

`endif

