//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// Tue Jul 30 2019 21:10:47
//
//      Input file      : 
//      Component name  : shiftamountreg
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------

//**************************************************************************************************** 
// Shifter control register for ARM7TDMI-S processor 
// Designed by Ruslan Lepetenok 
// Modified 11.11.2002 
//**************************************************************************************************** 

module shiftamountreg(
   nRESET,
   CLK,
   CLKEN,
   ShLenRsIn,
   ShLenRsOut
);
   // Clock and reset 
   input        nRESET;
   input        CLK;
   input        CLKEN;
   // Data signals 
   input [7:0]  ShLenRsIn;		// Shift amount for register shift (value of Rs[7..0])  
   output [7:0] ShLenRsOut;
   reg [7:0]    ShLenRsOut;
   
   
   
   always @(negedge nRESET or posedge CLK)
   begin: ShAmRg
      if (nRESET == 1'b0)		// Reset 
         ShLenRsOut <= {8{1'b0}};
      else 		// Clock	 
      begin
         if (CLKEN == 1'b1)		// Clock enable	  
            ShLenRsOut <= ShLenRsIn;
      end
   end
   
endmodule
